# Декоратор retry
Реализуйте декоратор retry, который принимает один аргумент:

* times — натуральное число

Декоратор должен выполнять повторную попытку вызова декорируемой функции, если во время ее выполнения возникает ошибка. Декоратор должен вызывать ее до тех пор, пока не исчерпает количество попыток times, после чего должен возбуждать исключение MaxRetriesException.

Также декоратор должен сохранять имя и строку документации декорируемой функции.

**Примечание 1.** Не забывайте про то, что декоратор не должен поглощать возвращаемое значение декорируемой функции.

**Примечание 2**. В тестирующую систему сдайте программу, содержащую только необходимый декоратор retry, но не код, вызывающий его. 

**Примечание 3**. Тестовые данные доступны по ссылке.

**Sample Input 1:**
```python
@retry(3)
def no_way():
    raise ValueError
   
try:
    no_way()
except Exception as e:
    print(type(e))
```
**Sample Output 1:**
```python
<class '__main__.MaxRetriesException'>
```
**Sample Input 2:**
```python
@retry(8)
def beegeek():
    beegeek.calls = beegeek.__dict__.get('calls', 0) + 1
    if beegeek.calls < 5:
        raise ValueError
    print('beegeek')
    
beegeek()
```
**Sample Output 2:**
```python
beegeek
```


# Solution
```python
from functools import wraps


class MaxRetriesException(Exception):
    ...


def retry(times):
    def decorator(func):

        @wraps(func)
        def wrapper(*args, **kwargs):
            nonlocal times

            while times:
                try:
                    return func(*args, **kwargs)
                except:
                    times -= 1
            else:
                raise MaxRetriesException

        return wrapper

    return decorator
```